; Sound Effects for song , version 2.0, generated by Arkos Tracker 2.

MyRing9Sound_SoundEffects
MyRing9Sound_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
MyRing9Sound_SoundEffectsDisarkPointerRegionStart0
	dw MyRing9Sound_SoundEffects_Sound1	; Sound effect 1.
MyRing9Sound_SoundEffectsDisarkPointerRegionEnd0

MyRing9Sound_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
MyRing9Sound_SoundEffects_Sound1
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 40	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 65	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 90	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 83	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 76	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 69	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 62	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 55	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 48	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 41	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 41	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 39	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 39	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 39	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 39	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 39	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 39	; Software period.

MyRing9Sound_SoundEffects_Sound1_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
MyRing9Sound_SoundEffectsDisarkPointerRegionStart2
	dw MyRing9Sound_SoundEffects_Sound1_Loop	; Loops here.
MyRing9Sound_SoundEffectsDisarkPointerRegionEnd2

MyRing9Sound_SoundEffectsDisarkByteRegionEnd1
