; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Untitled_Start
Untitled_StartDisarkGenerateExternalLabel

Untitled_DisarkByteRegionStart0
	db "AT20"
Untitled_DisarkPointerRegionStart1
	dw Untitled_ArpeggioTable	; The address of the Arpeggio table.
	dw Untitled_PitchTable	; The address of the Pitch table.
	dw Untitled_InstrumentTable	; The address of the Instrument table.
	dw Untitled_EffectBlockTable	; The address of the Effect Block table.
Untitled_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Untitled_DisarkPointerRegionStart2
	dw Untitled_Subsong0_Start
Untitled_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Untitled_ArpeggioTable
Untitled_DisarkPointerRegionStart3
Untitled_DisarkPointerRegionEnd3

; Declares all the Pitches.
Untitled_PitchTable
Untitled_DisarkPointerRegionStart4
Untitled_DisarkPointerRegionEnd4

; Declares all the Instruments.
Untitled_InstrumentTable
Untitled_DisarkPointerRegionStart5
	dw Untitled_EmptyInstrument
	dw Untitled_Instrument1
	dw Untitled_Instrument2
	dw Untitled_Instrument3
	dw Untitled_Instrument4
	dw Untitled_Instrument5
	dw Untitled_Instrument6
	dw Untitled_Instrument7
	dw Untitled_Instrument8
	dw Untitled_Instrument9
	dw Untitled_Instrument10
Untitled_DisarkPointerRegionEnd5

Untitled_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Untitled_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Untitled_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 65	; Additional data. Noise: 1. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw -1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 1	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw -1	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 41	; Soft only. Volume: 5.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 1	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 161	; Soft only. Volume: 4. Volume only.

	db 25	; Soft only. Volume: 3.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 6	; Loop to silence.

Untitled_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 10	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 8	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 2	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 1	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 1	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 240	; No Soft no Hard. Volume: 14. Noise? true.
	db 4	; Noise: 4.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 8	; Arpeggio.

	db 249	; Soft only. Volume: 15. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument4
	db 1	; The speed (>0, 0 for 256).
Untitled_Instrument4_Loop	db 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
Untitled_DisarkWordForceReference6
	dw Untitled_Instrument4_Loop	; Loop here.

Untitled_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 241	; Soft only. Volume: 14. Volume only.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 233	; Soft only. Volume: 13. Volume only.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 209	; Soft only. Volume: 10. Volume only.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 201	; Soft only. Volume: 9. Volume only.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 193	; Soft only. Volume: 8. Volume only.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 177	; Soft only. Volume: 6. Volume only.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 161	; Soft only. Volume: 4. Volume only.

	db 25	; Soft only. Volume: 3.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 145	; Soft only. Volume: 2. Volume only.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Untitled_Instrument6
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 193	; Soft only. Volume: 8. Volume only.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 169	; Soft only. Volume: 5. Volume only.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 153	; Soft only. Volume: 3. Volume only.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 145	; Soft only. Volume: 2. Volume only.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 6	; Loop to silence.

Untitled_Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 193	; Soft only. Volume: 8. Volume only.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 233	; Soft only. Volume: 13. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 185	; Soft only. Volume: 7. Volume only.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 6	; Loop to silence.

Untitled_Instrument8
	db 1	; The speed (>0, 0 for 256).
	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 4	; Noise: 4.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 11	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument9
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

Untitled_Instrument9_Loop	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 7	; Loop.
Untitled_DisarkWordForceReference7
	dw Untitled_Instrument9_Loop	; Loop here.

Untitled_Instrument10
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Untitled_EffectBlockTable
Untitled_DisarkPointerRegionStart8
	dw Untitled_EffectBlock_P4P0	; Index 0
	dw Untitled_EffectBlock_P4P3	; Index 1
	dw Untitled_EffectBlock_P4P2	; Index 2
	dw Untitled_EffectBlock_P4P4	; Index 3
	dw Untitled_EffectBlock_P4P1	; Index 4
	dw Untitled_EffectBlock_P20P128P0	; Index 5
	dw Untitled_EffectBlock_P18P0P2	; Index 6
	dw Untitled_EffectBlock_P4P5	; Index 7
	dw Untitled_EffectBlock_P4P6	; Index 8
	dw Untitled_EffectBlock_P4P7	; Index 9
	dw Untitled_EffectBlock_P4P8	; Index 10
	dw Untitled_EffectBlock_P20P128P1	; Index 11
	dw Untitled_EffectBlock_P18P0P1	; Index 12
	dw Untitled_EffectBlock_P20P0P2	; Index 13
Untitled_DisarkPointerRegionEnd8

Untitled_EffectBlock_P4P0
	db 4, 0
Untitled_EffectBlock_P4P1
	db 4, 1
Untitled_EffectBlock_P4P2
	db 4, 2
Untitled_EffectBlock_P4P3
	db 4, 3
Untitled_EffectBlock_P4P4
	db 4, 4
Untitled_EffectBlock_P4P5
	db 4, 5
Untitled_EffectBlock_P4P6
	db 4, 6
Untitled_EffectBlock_P4P7
	db 4, 7
Untitled_EffectBlock_P4P8
	db 4, 8
Untitled_EffectBlock_P20P128P0
	db 20, 128, 0
Untitled_EffectBlock_P20P128P1
	db 20, 128, 1
Untitled_EffectBlock_P18P0P1
	db 18, 0, 1
Untitled_EffectBlock_P18P0P2
	db 18, 0, 2
Untitled_EffectBlock_P20P0P2
	db 20, 0, 2

Untitled_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Untitled_Subsong0_DisarkByteRegionStart0
Untitled_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 2	; Loop start index (>=0).
	db 26	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 24	; Base note index (>=0).

Untitled_Subsong0_Linker
Untitled_Subsong0_DisarkPointerRegionStart1
; Position 0
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track1
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_LinkerBlock0

; Position 1
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track1
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 2
Untitled_Subsong0_Linker_Loop
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 3
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 4
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 5
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 6
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 7
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 8
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 9
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 10
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track14
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 11
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 12
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 13
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock0

; Position 14
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 15
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock0

; Position 16
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock2

; Position 17
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 18
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 19
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 20
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 21
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 22
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 23
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 24
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock3

; Position 25
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track14
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock4

; Position 26
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock4

Untitled_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Untitled_Subsong0_DisarkWordForceReference2
	dw Untitled_Subsong0_Linker_Loop

Untitled_Subsong0_LinkerBlock0
	db 24	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference3
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference4
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock1
	db 24	; Height.
	db -5	; Transposition 0.
	db -5	; Transposition 1.
	db 7	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference5
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference6
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock2
	db 24	; Height.
	db 7	; Transposition 0.
	db -5	; Transposition 1.
	db -5	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference7
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference8
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock3
	db 24	; Height.
	db -5	; Transposition 0.
	db -5	; Transposition 1.
	db -5	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference9
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference10
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock4
	db 24	; Height.
	db -7	; Transposition 0.
	db -7	; Transposition 1.
	db -7	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference11
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference12
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.

Untitled_Subsong0_Track0
	db 221
	db 10	; New Instrument (10).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 240
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 233
	db 10	; New Instrument (10).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 245
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 221
	db 10	; New Instrument (10).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 238
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 233
	db 10	; New Instrument (10).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 240
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 228
	db 6	; New Instrument (6).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 236
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 240
	db 6	; New Instrument (6).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 238
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 228
	db 6	; New Instrument (6).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 243
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 240
	db 6	; New Instrument (6).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 176
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track1
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track2
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 2	; Index to an effect block.
	db 197
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 2	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 2	; Index to an effect block.
	db 255
	db 19	; Escape note (19).
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 5
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 255
	db 19	; Escape note (19).
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 197
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track3
	db 221
	db 10	; New Instrument (10).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 240
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 233
	db 10	; New Instrument (10).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 245
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 221
	db 10	; New Instrument (10).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 238
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 233
	db 10	; New Instrument (10).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 240
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 228
	db 6	; New Instrument (6).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 236
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 240
	db 6	; New Instrument (6).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 238
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 228
	db 6	; New Instrument (6).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 243
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 240
	db 6	; New Instrument (6).
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track4
	db 133
	db 4	; New Instrument (4).
	db 8
	db 10
	db 12
	db 15
	db 16
	db 17
	db 60	; Waits for 1 line.

	db 209
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 69
	db 3	; Index to an effect block.
	db 84
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 72
	db 3	; Index to an effect block.
	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 3	; Index to an effect block.
	db 81
	db 0	; Index to an effect block.
	db 216
	db 9	; New Instrument (9).
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 88
	db 2	; Index to an effect block.
	db 41
	db 108
	db 4	; Index to an effect block.
	db 110
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track5
	db 240
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 46
	db 60	; Waits for 1 line.

	db 108
	db 1	; Index to an effect block.
	db 110
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 12	; Index to an effect block.
	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 157
	db 5	; New Instrument (5).
	db 145
	db 4	; New Instrument (4).
	db 160
	db 5	; New Instrument (5).
	db 34
	db 133
	db 4	; New Instrument (4).
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track6
	db 164
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 24
	db 17
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 133
	db 4	; New Instrument (4).
	db 145
	db 5	; New Instrument (5).
	db 29
	db 60	; Waits for 1 line.

	db 32
	db 27
	db 60	; Waits for 1 line.

	db 143
	db 4	; New Instrument (4).
	db 150
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 23
	db 24
	db 60	; Waits for 1 line.

	db 167
	db 9	; New Instrument (9).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 13	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track7
	db 228
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 133
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 169
	db 7	; New Instrument (7).
	db 145
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 172
	db 9	; New Instrument (9).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 162
	db 9	; New Instrument (9).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 131
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 167
	db 9	; New Instrument (9).
	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track8
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 2	; Index to an effect block.
	db 197
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 2	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 2	; Index to an effect block.
	db 255
	db 19	; Escape note (19).
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 5
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 255
	db 19	; Escape note (19).
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track9
	db 133
	db 4	; New Instrument (4).
	db 8
	db 10
	db 12
	db 15
	db 16
	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 5
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 15
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 12
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 0
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track10
	db 133
	db 4	; New Instrument (4).
	db 8
	db 10
	db 12
	db 15
	db 16
	db 17
	db 60	; Waits for 1 line.

	db 209
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 69
	db 3	; Index to an effect block.
	db 84
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 72
	db 3	; Index to an effect block.
	db 79
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 67
	db 3	; Index to an effect block.
	db 81
	db 0	; Index to an effect block.
	db 140
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 0
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track11
	db 240
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 46
	db 60	; Waits for 1 line.

	db 108
	db 1	; Index to an effect block.
	db 110
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 41
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 145
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 133
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track12
	db 221
	db 10	; New Instrument (10).
	db 10	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 240
	db 1	; New Instrument (1).
	db 9	; Index to an effect block.
	db 169
	db 10	; New Instrument (10).
	db 60	; Waits for 1 line.

	db 245
	db 1	; New Instrument (1).
	db 8	; Index to an effect block.
	db 157
	db 10	; New Instrument (10).
	db 60	; Waits for 1 line.

	db 238
	db 1	; New Instrument (1).
	db 7	; Index to an effect block.
	db 233
	db 10	; New Instrument (10).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 240
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 236
	db 1	; New Instrument (1).
	db 7	; Index to an effect block.
	db 240
	db 6	; New Instrument (6).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 238
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 228
	db 6	; New Instrument (6).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 243
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 240
	db 6	; New Instrument (6).
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track13
	db 199
	db 3	; New Instrument (3).
	db 10	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 9	; Index to an effect block.
	db 133
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 8	; Index to an effect block.
	db 135
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 221
	db 10	; New Instrument (10).
	db 7	; Index to an effect block.
	db 255
	db 19	; Escape note (19).
	db 8	; New Instrument (8).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 1	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 197
	db 2	; New Instrument (2).
	db 7	; Index to an effect block.
	db 69
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 228
	db 6	; New Instrument (6).
	db 1	; Index to an effect block.
	db 199
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 164
	db 6	; New Instrument (6).
	db 255
	db 19	; Escape note (19).
	db 8	; New Instrument (8).
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track14
	db 240
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 133
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 240
	db 9	; New Instrument (9).
	db 2	; Index to an effect block.
	db 145
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 255
	db 80	; Escape note (80).
	db 9	; New Instrument (9).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 55
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 124	; No note, but effects.
	db 3	; Index to an effect block.
	db 124	; No note, but effects.
	db 8	; Index to an effect block.
	db 110
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 131
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 179
	db 9	; New Instrument (9).
	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track15
	db 145
	db 4	; New Instrument (4).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 5
	db 128
	db 0	; New Instrument (0).
	db 133
	db 4	; New Instrument (4).
	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 5
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 15
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 128
	db 0	; New Instrument (0).
	db 131
	db 4	; New Instrument (4).
	db 15
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Untitled_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Untitled_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Untitled_Subsong0_DisarkByteRegionEnd0
