; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

MyFlappyBird2_Start
MyFlappyBird2_StartDisarkGenerateExternalLabel

MyFlappyBird2_DisarkByteRegionStart0
	db "AT20"
MyFlappyBird2_DisarkPointerRegionStart1
	dw MyFlappyBird2_ArpeggioTable	; The address of the Arpeggio table.
	dw MyFlappyBird2_PitchTable	; The address of the Pitch table.
	dw MyFlappyBird2_InstrumentTable	; The address of the Instrument table.
	dw MyFlappyBird2_EffectBlockTable	; The address of the Effect Block table.
MyFlappyBird2_DisarkPointerRegionEnd1


; The addresses of each Subsong:
MyFlappyBird2_DisarkPointerRegionStart2
	dw MyFlappyBird2_Subsong0_Start
MyFlappyBird2_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
MyFlappyBird2_ArpeggioTable
MyFlappyBird2_DisarkPointerRegionStart3
MyFlappyBird2_DisarkPointerRegionEnd3

; Declares all the Pitches.
MyFlappyBird2_PitchTable
MyFlappyBird2_DisarkPointerRegionStart4
MyFlappyBird2_DisarkPointerRegionEnd4

; Declares all the Instruments.
MyFlappyBird2_InstrumentTable
MyFlappyBird2_DisarkPointerRegionStart5
	dw MyFlappyBird2_EmptyInstrument
	dw MyFlappyBird2_Instrument1
	dw MyFlappyBird2_Instrument2
	dw MyFlappyBird2_Instrument3
	dw MyFlappyBird2_Instrument4
	dw MyFlappyBird2_Instrument5
	dw MyFlappyBird2_Instrument6
	dw MyFlappyBird2_Instrument7
	dw MyFlappyBird2_Instrument8
	dw MyFlappyBird2_Instrument9
	dw MyFlappyBird2_Instrument10
	dw MyFlappyBird2_Instrument11
	dw MyFlappyBird2_Instrument12
	dw MyFlappyBird2_Instrument13
	dw MyFlappyBird2_Instrument14
	dw MyFlappyBird2_Instrument15
	dw MyFlappyBird2_Instrument16
	dw MyFlappyBird2_Instrument17
MyFlappyBird2_DisarkPointerRegionEnd5

MyFlappyBird2_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
MyFlappyBird2_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

MyFlappyBird2_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 10	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 6	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 6	; Loop to silence.

MyFlappyBird2_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 75	; Additional data. Noise: 11. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 74	; Additional data. Noise: 10. Pitch? false. Arp? true. Period? false.
	db 13	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 73	; Additional data. Noise: 9. Pitch? false. Arp? true. Period? false.
	db 16	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 72	; Additional data. Noise: 8. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 7	; Additional data. Noise: 7. Pitch? false. Arp? false. Period? false.

	db 81	; Soft only. Volume: 10.
	db 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 69	; Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	db 14	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 4	; Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

	db 33	; Soft only. Volume: 4.
	db 3	; Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	db 25	; Soft only. Volume: 3.
	db 2	; Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	db 6	; Loop to silence.

MyFlappyBird2_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 6	; Loop to silence.

MyFlappyBird2_Instrument4
	db 1	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument4_Loop	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 130	; Simple case. Ratio: 5

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference6
	dw MyFlappyBird2_Instrument4_Loop	; Loop here.

MyFlappyBird2_Instrument5
	db 1	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument5_Loop	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference7
	dw MyFlappyBird2_Instrument5_Loop	; Loop here.

MyFlappyBird2_Instrument6
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 65	; Additional data. Noise: 1. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 249	; Soft only. Volume: 15. Volume only.

	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 6	; Loop to silence.

MyFlappyBird2_Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 233	; Soft only. Volume: 13. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 6	; Loop to silence.

MyFlappyBird2_Instrument8
	db 2	; The speed (>0, 0 for 256).
	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 133	; Simple case. Ratio: 2

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 133	; Simple case. Ratio: 2

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 133	; Simple case. Ratio: 2

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 133	; Simple case. Ratio: 2

MyFlappyBird2_Instrument8_Loop	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 21	; Complex case. Ratio: 2
	dw -1	; Pitch.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 133	; Simple case. Ratio: 2

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 21	; Complex case. Ratio: 2
	dw 1	; Pitch.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference8
	dw MyFlappyBird2_Instrument8_Loop	; Loop here.

MyFlappyBird2_Instrument9
	db 1	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument9_Loop	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 132	; Simple case. Ratio: 3

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference9
	dw MyFlappyBird2_Instrument9_Loop	; Loop here.

MyFlappyBird2_Instrument10
	db 2	; The speed (>0, 0 for 256).
	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 38	; Complex case. Ratio: 1
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 38	; Complex case. Ratio: 1
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 12	; Arpeggio.

MyFlappyBird2_Instrument10_Loop	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 54	; Complex case. Ratio: 1
	db 12	; Arpeggio.
	dw -1	; Pitch.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 38	; Complex case. Ratio: 1
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 53	; Complex case. Ratio: 2
	db 12	; Arpeggio.
	dw 1	; Pitch.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference10
	dw MyFlappyBird2_Instrument10_Loop	; Loop here.

MyFlappyBird2_Instrument11
	db 1	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument11_Loop	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 2	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 14	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 15	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 19	; Arpeggio.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference11
	dw MyFlappyBird2_Instrument11_Loop	; Loop here.

MyFlappyBird2_Instrument12
	db 1	; The speed (>0, 0 for 256).
	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 12	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 37	; Complex case. Ratio: 2
	db 24	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

MyFlappyBird2_Instrument12_Loop	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference12
	dw MyFlappyBird2_Instrument12_Loop	; Loop here.

MyFlappyBird2_Instrument13
	db 3	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument13_Loop	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference13
	dw MyFlappyBird2_Instrument13_Loop	; Loop here.

MyFlappyBird2_Instrument14
	db 1	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument14_Loop	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 2	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 14	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 16	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 19	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference14
	dw MyFlappyBird2_Instrument14_Loop	; Loop here.

MyFlappyBird2_Instrument15
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

MyFlappyBird2_Instrument15_Loop	db 105	; Soft only. Volume: 13.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 12	; Arpeggio.
	dw -1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 233	; Soft only. Volume: 13. Volume only.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference15
	dw MyFlappyBird2_Instrument15_Loop	; Loop here.

MyFlappyBird2_Instrument16
	db 2	; The speed (>0, 0 for 256).
MyFlappyBird2_Instrument16_Loop	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 7	; Loop.
MyFlappyBird2_DisarkWordForceReference16
	dw MyFlappyBird2_Instrument16_Loop	; Loop here.

MyFlappyBird2_Instrument17
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 24	; Arpeggio.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
MyFlappyBird2_EffectBlockTable
MyFlappyBird2_DisarkPointerRegionStart17
	dw MyFlappyBird2_EffectBlock_P4P3	; Index 0
	dw MyFlappyBird2_EffectBlock_P4P2	; Index 1
	dw MyFlappyBird2_EffectBlock_P4P0	; Index 2
	dw MyFlappyBird2_EffectBlock_P4P1	; Index 3
	dw MyFlappyBird2_EffectBlock_P20P128P0	; Index 4
	dw MyFlappyBird2_EffectBlock_P18P128P0	; Index 5
	dw MyFlappyBird2_EffectBlock_P18P0P1	; Index 6
	dw MyFlappyBird2_EffectBlock_P20P0P2	; Index 7
	dw MyFlappyBird2_EffectBlock_P4P4	; Index 8
	dw MyFlappyBird2_EffectBlock_P20P128P2	; Index 9
	dw MyFlappyBird2_EffectBlock_P20P0P1	; Index 10
	dw MyFlappyBird2_EffectBlock_P18P128P3	; Index 11
	dw MyFlappyBird2_EffectBlock_P18P0P3	; Index 12
	dw MyFlappyBird2_EffectBlock_P18P128P7	; Index 13
	dw MyFlappyBird2_EffectBlock_P20P0P16	; Index 14
	dw MyFlappyBird2_EffectBlock_P5P1P18P128P0	; Index 15
	dw MyFlappyBird2_EffectBlock_P20P128P6	; Index 16
	dw MyFlappyBird2_EffectBlock_P18P0P16	; Index 17
	dw MyFlappyBird2_EffectBlock_P18P0P24	; Index 18
	dw MyFlappyBird2_EffectBlock_P18P0P40	; Index 19
	dw MyFlappyBird2_EffectBlock_P18P0P2	; Index 20
	dw MyFlappyBird2_EffectBlock_P18P0P8	; Index 21
	dw MyFlappyBird2_EffectBlock_P18P128P4	; Index 22
	dw MyFlappyBird2_EffectBlock_P20P0P3	; Index 23
	dw MyFlappyBird2_EffectBlock_P20P0P4	; Index 24
	dw MyFlappyBird2_EffectBlock_P20P0P8	; Index 25
	dw MyFlappyBird2_EffectBlock_P4P5	; Index 26
	dw MyFlappyBird2_EffectBlock_P4P6	; Index 27
	dw MyFlappyBird2_EffectBlock_P4P7	; Index 28
	dw MyFlappyBird2_EffectBlock_P4P8	; Index 29
MyFlappyBird2_DisarkPointerRegionEnd17

MyFlappyBird2_EffectBlock_P4P0
	db 4, 0
MyFlappyBird2_EffectBlock_P4P1
	db 4, 1
MyFlappyBird2_EffectBlock_P4P2
	db 4, 2
MyFlappyBird2_EffectBlock_P4P3
	db 4, 3
MyFlappyBird2_EffectBlock_P4P4
	db 4, 4
MyFlappyBird2_EffectBlock_P4P5
	db 4, 5
MyFlappyBird2_EffectBlock_P4P6
	db 4, 6
MyFlappyBird2_EffectBlock_P4P7
	db 4, 7
MyFlappyBird2_EffectBlock_P4P8
	db 4, 8
MyFlappyBird2_EffectBlock_P20P128P0
	db 20, 128, 0
MyFlappyBird2_EffectBlock_P20P128P2
	db 20, 128, 2
MyFlappyBird2_EffectBlock_P20P128P6
	db 20, 128, 6
MyFlappyBird2_EffectBlock_P18P0P16
	db 18, 0, 16
MyFlappyBird2_EffectBlock_P18P0P24
	db 18, 0, 24
MyFlappyBird2_EffectBlock_P18P0P40
	db 18, 0, 40
MyFlappyBird2_EffectBlock_P18P0P1
	db 18, 0, 1
MyFlappyBird2_EffectBlock_P18P0P2
	db 18, 0, 2
MyFlappyBird2_EffectBlock_P18P0P3
	db 18, 0, 3
MyFlappyBird2_EffectBlock_P18P0P8
	db 18, 0, 8
MyFlappyBird2_EffectBlock_P18P128P0
	db 18, 128, 0
MyFlappyBird2_EffectBlock_P18P128P3
	db 18, 128, 3
MyFlappyBird2_EffectBlock_P18P128P4
	db 18, 128, 4
MyFlappyBird2_EffectBlock_P18P128P7
	db 18, 128, 7
MyFlappyBird2_EffectBlock_P20P0P16
	db 20, 0, 16
MyFlappyBird2_EffectBlock_P20P0P1
	db 20, 0, 1
MyFlappyBird2_EffectBlock_P20P0P2
	db 20, 0, 2
MyFlappyBird2_EffectBlock_P20P0P3
	db 20, 0, 3
MyFlappyBird2_EffectBlock_P20P0P4
	db 20, 0, 4
MyFlappyBird2_EffectBlock_P20P0P8
	db 20, 0, 8
MyFlappyBird2_EffectBlock_P5P1P18P128P0
	db 5, 1, 18, 128, 0

MyFlappyBird2_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
MyFlappyBird2_Subsong0_DisarkByteRegionStart0
MyFlappyBird2_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 14	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 23	; Base note index (>=0).

MyFlappyBird2_Subsong0_Linker
MyFlappyBird2_Subsong0_DisarkPointerRegionStart1
; Position 0
MyFlappyBird2_Subsong0_Linker_Loop
	dw MyFlappyBird2_Subsong0_Track1
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track2
	dw MyFlappyBird2_Subsong0_LinkerBlock0

; Position 1
	dw MyFlappyBird2_Subsong0_Track3
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track4
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 2
	dw MyFlappyBird2_Subsong0_Track6
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track5
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 3
	dw MyFlappyBird2_Subsong0_Track3
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track7
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 4
	dw MyFlappyBird2_Subsong0_Track9
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track8
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 5
	dw MyFlappyBird2_Subsong0_Track12
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track13
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 6
	dw MyFlappyBird2_Subsong0_Track14
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track15
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 7
	dw MyFlappyBird2_Subsong0_Track16
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track17
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 8
	dw MyFlappyBird2_Subsong0_Track14
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track20
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 9
	dw MyFlappyBird2_Subsong0_Track16
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track21
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 10
	dw MyFlappyBird2_Subsong0_Track18
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track19
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 11
	dw MyFlappyBird2_Subsong0_Track22
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track23
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 12
	dw MyFlappyBird2_Subsong0_Track24
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track25
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 13
	dw MyFlappyBird2_Subsong0_Track10
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track11
	dw MyFlappyBird2_Subsong0_LinkerBlock1

; Position 14
	dw MyFlappyBird2_Subsong0_Track26
	dw MyFlappyBird2_Subsong0_Track0
	dw MyFlappyBird2_Subsong0_Track27
	dw MyFlappyBird2_Subsong0_LinkerBlock1

MyFlappyBird2_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
MyFlappyBird2_Subsong0_DisarkWordForceReference2
	dw MyFlappyBird2_Subsong0_Linker_Loop

MyFlappyBird2_Subsong0_LinkerBlock0
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
MyFlappyBird2_Subsong0_DisarkWordForceReference3
	dw MyFlappyBird2_Subsong0_SpeedTrack0	; SpeedTrack address.
MyFlappyBird2_Subsong0_DisarkWordForceReference4
	dw MyFlappyBird2_Subsong0_EventTrack0	; EventTrack address.
MyFlappyBird2_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
MyFlappyBird2_Subsong0_DisarkWordForceReference5
	dw MyFlappyBird2_Subsong0_SpeedTrack0	; SpeedTrack address.
MyFlappyBird2_Subsong0_DisarkWordForceReference6
	dw MyFlappyBird2_Subsong0_EventTrack0	; EventTrack address.

MyFlappyBird2_Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track1
	db 133
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 133
	db 4	; New Instrument (4).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 133
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 60	; Waits for 1 line.

	db 145
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track2
	db 209
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 17
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track3
	db 193
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 133
	db 6	; New Instrument (6).
	db 17
	db 5
	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 5
	db 129
	db 1	; New Instrument (1).
	db 145
	db 6	; New Instrument (6).
	db 5
	db 141
	db 2	; New Instrument (2).
	db 136
	db 6	; New Instrument (6).
	db 10
	db 12
	db 129
	db 1	; New Instrument (1).
	db 129
	db 6	; New Instrument (6).
	db 1
	db 13
	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 8
	db 129
	db 1	; New Instrument (1).
	db 1
	db 141
	db 6	; New Instrument (6).
	db 15
	db 141
	db 2	; New Instrument (2).
	db 145
	db 6	; New Instrument (6).
	db 20
	db 141
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 128
	db 6	; New Instrument (6).
	db 0
	db 12
	db 141
	db 2	; New Instrument (2).
	db 191
	db 21	; Escape note (21).
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 1
	db 60	; Waits for 1 line.

	db 191
	db 21	; Escape note (21).
	db 6	; New Instrument (6).
	db 0
	db 12
	db 141
	db 2	; New Instrument (2).
	db 143
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 146
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 146
	db 6	; New Instrument (6).
	db 20
	db 22
	db 141
	db 2	; New Instrument (2).
	db 141
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 129
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 1
	db 134
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 136
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 13
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track4
	db 221
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 30
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track5
	db 221
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 32
	db 226
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 221
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 217
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 229
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 224
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 219
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 216
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 221
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 219
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 223
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 219
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 219
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 216
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 223
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 219
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 228
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 219
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 223
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 219
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 228
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 223
	db 3	; New Instrument (3).
	db 0	; Index to an effect block.
	db 231
	db 7	; New Instrument (7).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 25
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track6
	db 193
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 133
	db 6	; New Instrument (6).
	db 17
	db 5
	db 141
	db 2	; New Instrument (2).
	db 135
	db 6	; New Instrument (6).
	db 7
	db 129
	db 1	; New Instrument (1).
	db 1
	db 136
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 136
	db 6	; New Instrument (6).
	db 129
	db 2	; New Instrument (2).
	db 136
	db 6	; New Instrument (6).
	db 22
	db 24
	db 129
	db 1	; New Instrument (1).
	db 129
	db 6	; New Instrument (6).
	db 1
	db 3
	db 141
	db 2	; New Instrument (2).
	db 131
	db 6	; New Instrument (6).
	db 3
	db 5
	db 129
	db 1	; New Instrument (1).
	db 1
	db 141
	db 6	; New Instrument (6).
	db 15
	db 141
	db 2	; New Instrument (2).
	db 145
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 141
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 128
	db 6	; New Instrument (6).
	db 0
	db 0
	db 141
	db 2	; New Instrument (2).
	db 131
	db 6	; New Instrument (6).
	db 3
	db 129
	db 1	; New Instrument (1).
	db 131
	db 6	; New Instrument (6).
	db 5
	db 129
	db 1	; New Instrument (1).
	db 135
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 131
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 143
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 13
	db 13
	db 13
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 13
	db 13
	db 13
	db 13
	db 129
	db 1	; New Instrument (1).
	db 134
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 1
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track7
	db 169
	db 10	; New Instrument (10).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 37
	db 61, 6	; Waits for 7 lines.

	db 39
	db 37
	db 36
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 43
	db 61, 6	; Waits for 7 lines.

	db 41
	db 43
	db 46
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 34
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 30
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track8
	db 169
	db 8	; New Instrument (8).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 241
	db 3	; New Instrument (3).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 44
	db 49
	db 41
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 183
	db 8	; New Instrument (8).
	db 63
	db 79	; Escape note (79).
	db 55
	db 60	; Waits for 1 line.

	db 51
	db 46
	db 44
	db 43
	db 124	; No note, but effects.
	db 24	; Index to an effect block.
	db 124	; No note, but effects.
	db 16	; Index to an effect block.
	db 39
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 63
	db 79	; Escape note (79).
	db 60	; Waits for 1 line.

	db 63
	db 81	; Escape note (81).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 63
	db 81	; Escape note (81).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track9
	db 193
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 133
	db 6	; New Instrument (6).
	db 17
	db 5
	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 5
	db 129
	db 1	; New Instrument (1).
	db 145
	db 6	; New Instrument (6).
	db 5
	db 141
	db 2	; New Instrument (2).
	db 136
	db 6	; New Instrument (6).
	db 10
	db 12
	db 129
	db 1	; New Instrument (1).
	db 129
	db 6	; New Instrument (6).
	db 1
	db 13
	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 8
	db 129
	db 1	; New Instrument (1).
	db 1
	db 141
	db 6	; New Instrument (6).
	db 15
	db 141
	db 2	; New Instrument (2).
	db 145
	db 6	; New Instrument (6).
	db 20
	db 141
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 128
	db 6	; New Instrument (6).
	db 0
	db 12
	db 141
	db 2	; New Instrument (2).
	db 191
	db 21	; Escape note (21).
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 1
	db 60	; Waits for 1 line.

	db 191
	db 21	; Escape note (21).
	db 6	; New Instrument (6).
	db 0
	db 12
	db 141
	db 2	; New Instrument (2).
	db 143
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 146
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 13
	db 148
	db 6	; New Instrument (6).
	db 22
	db 10
	db 13
	db 141
	db 2	; New Instrument (2).
	db 13
	db 129
	db 6	; New Instrument (6).
	db 129
	db 1	; New Instrument (1).
	db 1
	db 134
	db 6	; New Instrument (6).
	db 141
	db 2	; New Instrument (2).
	db 13
	db 13
	db 13
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track10
	db 133
	db 9	; New Instrument (9).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track11
	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 157
	db 11	; New Instrument (11).
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 157
	db 11	; New Instrument (11).
	db 60	; Waits for 1 line.

	db 169
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 169
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 169
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 8	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 8	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track12
	db 193
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 133
	db 13	; New Instrument (13).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 141
	db 2	; New Instrument (2).
	db 133
	db 13	; New Instrument (13).
	db 129
	db 1	; New Instrument (1).
	db 197
	db 13	; New Instrument (13).
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 61, 5	; Waits for 6 lines.

	db 141
	db 1	; New Instrument (1).
	db 136
	db 13	; New Instrument (13).
	db 60	; Waits for 1 line.

	db 141
	db 1	; New Instrument (1).
	db 200
	db 13	; New Instrument (13).
	db 12	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 141
	db 2	; New Instrument (2).
	db 205
	db 13	; New Instrument (13).
	db 4	; Index to an effect block.
	db 124	; No note, but effects.
	db 10	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 1
	db 140
	db 13	; New Instrument (13).
	db 129
	db 1	; New Instrument (1).
	db 140
	db 13	; New Instrument (13).
	db 141
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 140
	db 13	; New Instrument (13).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 7	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 9	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 141
	db 1	; New Instrument (1).
	db 134
	db 13	; New Instrument (13).
	db 60	; Waits for 1 line.

	db 141
	db 1	; New Instrument (1).
	db 198
	db 13	; New Instrument (13).
	db 7	; Index to an effect block.
	db 124	; No note, but effects.
	db 9	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 1	; New Instrument (1).
	db 131
	db 13	; New Instrument (13).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 13	; Index to an effect block.
	db 141
	db 2	; New Instrument (2).
	db 13
	db 136
	db 13	; New Instrument (13).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track13
	db 197
	db 13	; New Instrument (13).
	db 15	; Index to an effect block.
	db 61, 7	; Waits for 8 lines.

	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 61, 5	; Waits for 6 lines.

	db 72
	db 5	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 12	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 77
	db 5	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 124	; No note, but effects.
	db 10	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 5	; Index to an effect block.
	db 61, 7	; Waits for 8 lines.

	db 124	; No note, but effects.
	db 7	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 9	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 70
	db 5	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 7	; Index to an effect block.
	db 124	; No note, but effects.
	db 9	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 67
	db 5	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 124	; No note, but effects.
	db 13	; Index to an effect block.
	db 72
	db 5	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track14
	db 193
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 191
	db 16	; Escape note (16).
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 193
	db 1	; New Instrument (1).
	db 3	; Index to an effect block.
	db 255
	db 16	; Escape note (16).
	db 16	; New Instrument (16).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 193
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 255
	db 16	; Escape note (16).
	db 16	; New Instrument (16).
	db 2	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 124	; No note, but effects.
	db 21	; Index to an effect block.
	db 124	; No note, but effects.
	db 17	; Index to an effect block.
	db 124	; No note, but effects.
	db 18	; Index to an effect block.
	db 124	; No note, but effects.
	db 19	; Index to an effect block.
	db 153
	db 2	; New Instrument (2).
	db 131
	db 16	; New Instrument (16).
	db 61, 11	; Waits for 12 lines.

	db 165
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 1
	db 191
	db 18	; Escape note (18).
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 191
	db 18	; Escape note (18).
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 153
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 191
	db 18	; Escape note (18).
	db 16	; New Instrument (16).
	db 61, 6	; Waits for 7 lines.

	db 129
	db 1	; New Instrument (1).
	db 191
	db 17	; Escape note (17).
	db 16	; New Instrument (16).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 20	; Index to an effect block.
	db 124	; No note, but effects.
	db 11	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 153
	db 2	; New Instrument (2).
	db 129
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 153
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 193
	db 16	; New Instrument (16).
	db 22	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track15
	db 245
	db 15	; New Instrument (15).
	db 3	; Index to an effect block.
	db 61, 12	; Waits for 13 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 51
	db 61, 8	; Waits for 9 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 10	; Index to an effect block.
	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 46
	db 61, 21	; Waits for 22 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 48
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 10	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 124	; No note, but effects.
	db 6	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track16
	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 141
	db 2	; New Instrument (2).
	db 133
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 129
	db 1	; New Instrument (1).
	db 135
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 135
	db 16	; New Instrument (16).
	db 61, 6	; Waits for 7 lines.

	db 8
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 138
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 138
	db 16	; New Instrument (16).
	db 61, 6	; Waits for 7 lines.

	db 141
	db 2	; New Instrument (2).
	db 140
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 1
	db 141
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 141
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 141
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 15
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 129
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track17
	db 236
	db 15	; New Instrument (15).
	db 3	; Index to an effect block.
	db 61, 11	; Waits for 12 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 60	; Waits for 1 line.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 61, 14	; Waits for 15 lines.

	db 46
	db 48
	db 49
	db 60	; Waits for 1 line.

	db 110
	db 8	; Index to an effect block.
	db 48
	db 49
	db 60	; Waits for 1 line.

	db 110
	db 3	; Index to an effect block.
	db 48
	db 49
	db 60	; Waits for 1 line.

	db 46
	db 112
	db 8	; Index to an effect block.
	db 115
	db 3	; Index to an effect block.
	db 49
	db 48
	db 49
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track18
	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 153
	db 2	; New Instrument (2).
	db 133
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 129
	db 1	; New Instrument (1).
	db 133
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 129
	db 1	; New Instrument (1).
	db 135
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 135
	db 16	; New Instrument (16).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 153
	db 2	; New Instrument (2).
	db 135
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 129
	db 1	; New Instrument (1).
	db 136
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 138
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 138
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 138
	db 16	; New Instrument (16).
	db 153
	db 2	; New Instrument (2).
	db 138
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 153
	db 2	; New Instrument (2).
	db 140
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 1
	db 141
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 141
	db 16	; New Instrument (16).
	db 60	; Waits for 1 line.

	db 129
	db 1	; New Instrument (1).
	db 141
	db 16	; New Instrument (16).
	db 153
	db 2	; New Instrument (2).
	db 143
	db 16	; New Instrument (16).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 129
	db 2	; New Instrument (2).
	db 129
	db 1	; New Instrument (1).
	db 145
	db 16	; New Instrument (16).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 152
	db 12	; New Instrument (12).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 29
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 22
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 27
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 61, 5	; Waits for 6 lines.

	db 22
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 27
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 22
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 18
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 36
	db 60	; Waits for 1 line.

	db 37
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track20
	db 245
	db 15	; New Instrument (15).
	db 3	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 55
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 7	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 51
	db 61, 6	; Waits for 7 lines.

	db 124	; No note, but effects.
	db 23	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 41
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 44
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 60	; Waits for 1 line.

	db 108
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 107
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 103
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 100
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 98
	db 0	; Index to an effect block.
	db 91
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 27
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 30
	db 60	; Waits for 1 line.

	db 34
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track21
	db 61, 8	; Waits for 9 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 61, 5	; Waits for 6 lines.

	db 226
	db 15	; New Instrument (15).
	db 3	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 32
	db 34
	db 39
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 37
	db 36
	db 37
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 27
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 54
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track22
	db 129
	db 1	; New Instrument (1).
	db 133
	db 17	; New Instrument (17).
	db 5
	db 129
	db 1	; New Instrument (1).
	db 141
	db 2	; New Instrument (2).
	db 133
	db 17	; New Instrument (17).
	db 5
	db 129
	db 1	; New Instrument (1).
	db 141
	db 2	; New Instrument (2).
	db 133
	db 17	; New Instrument (17).
	db 5
	db 129
	db 1	; New Instrument (1).
	db 133
	db 17	; New Instrument (17).
	db 5
	db 129
	db 1	; New Instrument (1).
	db 133
	db 17	; New Instrument (17).
	db 129
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 129
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 141
	db 2	; New Instrument (2).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 3
	db 129
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 129
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 129
	db 1	; New Instrument (1).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 129
	db 1	; New Instrument (1).
	db 141
	db 2	; New Instrument (2).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 129
	db 1	; New Instrument (1).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 129
	db 1	; New Instrument (1).
	db 1
	db 141
	db 2	; New Instrument (2).
	db 134
	db 17	; New Instrument (17).
	db 18
	db 6
	db 129
	db 1	; New Instrument (1).
	db 132
	db 17	; New Instrument (17).
	db 4
	db 129
	db 1	; New Instrument (1).
	db 141
	db 2	; New Instrument (2).
	db 132
	db 17	; New Instrument (17).
	db 129
	db 1	; New Instrument (1).
	db 132
	db 17	; New Instrument (17).
	db 4
	db 129
	db 1	; New Instrument (1).
	db 139
	db 17	; New Instrument (17).
	db 10
	db 141
	db 2	; New Instrument (2).
	db 13
	db 129
	db 1	; New Instrument (1).
	db 139
	db 17	; New Instrument (17).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track23
	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 233
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 221
	db 11	; New Instrument (11).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 231
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 219
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 231
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 219
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 231
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 219
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 231
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 219
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 234
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 222
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 234
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 222
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 234
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 222
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 234
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 222
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 232
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 220
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 232
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 220
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 232
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 220
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 232
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 220
	db 14	; New Instrument (14).
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track24
	db 205
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 133
	db 17	; New Instrument (17).
	db 5
	db 5
	db 5
	db 5
	db 141
	db 1	; New Instrument (1).
	db 133
	db 17	; New Instrument (17).
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 141
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 141
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 3
	db 3
	db 141
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 141
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 3
	db 141
	db 1	; New Instrument (1).
	db 131
	db 17	; New Instrument (17).
	db 141
	db 1	; New Instrument (1).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 141
	db 1	; New Instrument (1).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 6
	db 6
	db 141
	db 1	; New Instrument (1).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 141
	db 1	; New Instrument (1).
	db 134
	db 17	; New Instrument (17).
	db 6
	db 6
	db 6
	db 141
	db 1	; New Instrument (1).
	db 132
	db 17	; New Instrument (17).
	db 4
	db 141
	db 1	; New Instrument (1).
	db 132
	db 17	; New Instrument (17).
	db 4
	db 4
	db 4
	db 141
	db 1	; New Instrument (1).
	db 132
	db 17	; New Instrument (17).
	db 4
	db 141
	db 1	; New Instrument (1).
	db 139
	db 17	; New Instrument (17).
	db 10
	db 141
	db 1	; New Instrument (1).
	db 138
	db 17	; New Instrument (17).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track25
	db 152
	db 4	; New Instrument (4).
	db 20
	db 17
	db 12
	db 24
	db 20
	db 17
	db 12
	db 24
	db 20
	db 17
	db 12
	db 24
	db 20
	db 17
	db 12
	db 22
	db 147
	db 5	; New Instrument (5).
	db 15
	db 138
	db 4	; New Instrument (4).
	db 22
	db 147
	db 5	; New Instrument (5).
	db 15
	db 138
	db 4	; New Instrument (4).
	db 22
	db 147
	db 5	; New Instrument (5).
	db 15
	db 138
	db 4	; New Instrument (4).
	db 7
	db 10
	db 3
	db 60	; Waits for 1 line.

	db 6
	db 10
	db 13
	db 10
	db 13
	db 18
	db 13
	db 18
	db 22
	db 18
	db 22
	db 153
	db 5	; New Instrument (5).
	db 150
	db 4	; New Instrument (4).
	db 153
	db 5	; New Instrument (5).
	db 30
	db 34
	db 175
	db 9	; New Instrument (9).
	db 46
	db 42
	db 37
	db 35
	db 34
	db 35
	db 37
	db 35
	db 34
	db 148
	db 4	; New Instrument (4).
	db 156
	db 9	; New Instrument (9).
	db 139
	db 4	; New Instrument (4).
	db 8
	db 4
	db 11
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track26
	db 133
	db 4	; New Instrument (4).
	db 61, 6	; Waits for 7 lines.

	db 124	; No note, but effects.
	db 14	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 25	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 63
	db 16	; Escape note (16).
	db 61, 18	; Waits for 19 lines.

	db 124	; No note, but effects.
	db 14	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


MyFlappyBird2_Subsong0_Track27
	db 221
	db 7	; New Instrument (7).
	db 3	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 8	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 26	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 27	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 28	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 93
	db 29	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
MyFlappyBird2_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
MyFlappyBird2_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

MyFlappyBird2_Subsong0_DisarkByteRegionEnd0
