; Sound Effects for song MyRing4Sound, version 2.0, generated by Arkos Tracker 2.

MyRing4Sound_SoundEffects
MyRing4Sound_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
MyRing4Sound_SoundEffectsDisarkPointerRegionStart0
	dw MyRing4Sound_SoundEffects_Sound1	; Sound effect 1.
MyRing4Sound_SoundEffectsDisarkPointerRegionEnd0

MyRing4Sound_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
MyRing4Sound_SoundEffects_Sound1
	db 0	; Speed

	db 57	; Soft only. Volume: 14.
	dw 51	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 50	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 51	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 51	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 51	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 75	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 74	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 75	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 74	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 75	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 38	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 37	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 38	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 38	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 38	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 38	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 38	; Software period.

MyRing4Sound_SoundEffects_Sound1_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
MyRing4Sound_SoundEffectsDisarkPointerRegionStart2
	dw MyRing4Sound_SoundEffects_Sound1_Loop	; Loops here.
MyRing4Sound_SoundEffectsDisarkPointerRegionEnd2

MyRing4Sound_SoundEffectsDisarkByteRegionEnd1
