; Sound Effects for song MyRing1Sound, version 2.0, generated by Arkos Tracker 2.

MyRing1Sound_SoundEffects
MyRing1Sound_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
MyRing1Sound_SoundEffectsDisarkPointerRegionStart0
	dw MyRing1Sound_SoundEffects_Sound1	; Sound effect 1.
MyRing1Sound_SoundEffectsDisarkPointerRegionEnd0

MyRing1Sound_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
MyRing1Sound_SoundEffects_Sound1
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 90	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 115	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 140	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 133	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 126	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 119	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 112	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 105	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 98	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 91	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 91	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 89	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 89	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 89	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 89	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 89	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 89	; Software period.

MyRing1Sound_SoundEffects_Sound1_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
MyRing1Sound_SoundEffectsDisarkPointerRegionStart2
	dw MyRing1Sound_SoundEffects_Sound1_Loop	; Loops here.
MyRing1Sound_SoundEffectsDisarkPointerRegionEnd2

MyRing1Sound_SoundEffectsDisarkByteRegionEnd1
