; Sound Effects for song MyRing6Sound, version 2.0, generated by Arkos Tracker 2.

MyRing6Sound_SoundEffects
MyRing6Sound_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
MyRing6Sound_SoundEffectsDisarkPointerRegionStart0
	dw MyRing6Sound_SoundEffects_Sound1	; Sound effect 1.
MyRing6Sound_SoundEffectsDisarkPointerRegionEnd0

MyRing6Sound_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
MyRing6Sound_SoundEffects_Sound1
	db 0	; Speed

	db 57	; Soft only. Volume: 14.
	dw 43	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 42	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 43	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 43	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 43	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 67	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 66	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 67	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 66	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 67	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 30	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 29	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 30	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 30	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 30	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 30	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 30	; Software period.

MyRing6Sound_SoundEffects_Sound1_Loop	db 0	; No soft, no hard. Volume: 0.

	db 4	; End of the sound effect.

MyRing6Sound_SoundEffectsDisarkByteRegionEnd1
